### ISSUE TITLE
fdsnxml2inv - import_inv dlsv : slow sampling rate ( a sample/ 600s)  mishandled

### ISSUE THREAD

**Issue by lemarchandarnaud** [SeisComP3/seiscomp3#108]
Dear Jan
The SEED format encodes the sampling rate of channels with this format :  #.####E-##.
In one of  my dataless SEED, the sampling rate is 1.6667e-3.  dlsv tool  convert  1/1.6667e-3  into 597sec/sample. We identified this this as a bug to fixed.
thanks
arnaud

**Comment by gempa-jabe** [comment]
Is that still the case, even with commit 4fe3ecb8b54d0a6cf2dd67313952d1d27ca3343e? According the your tests this has been fixed already, correct?

**Comment by lemarchandarnaud** [comment]
correct.
 I am tracking all the issues I have see. This bug can be moderated as fixed.
