### ISSUE TITLE
Inventory: polynomial responses Gain=0

### ISSUE THREAD

**Issue by lemarchandarnaud** [SeisComP3/seiscomp3#109]
Dear Jan,

When  polynomial responses are detected the gains of streams, CalibrationSensor, and Repsonsespolynomial  are  set to zero. These gains doesn't make sense to me for a polynomial response. I think tey should remaoin empty?
Thanks 
arnaud

**Comment by gempa-jabe** [comment]
This should have been fixed in branch dlsv-conversion-fix. Can we use that one as a reference and update the status here in the ticket? I think that has been fixed there as well.

**Comment by lemarchandarnaud** [comment]
Correct. 
the branch dlsv-conversion-fix has sorted out this issue.
