### ISSUE TITLE
fdsnxml2inv - import_inv dlsv : Auxiliaries channels

### ISSUE THREAD

**Issue by lemarchandarnaud** [SeisComP3/seiscomp3#111]
Dear Jan
The channels fo dataless SEED of stationXML with unknown  input units (different from m, m/s,m/s^2)
are considered as auxiliaries channels. Thus , no intruments responses are set in the inventory.
Regards.
Arnaud

**Comment by gempa-jabe** [comment]
This has been implemented in branch ```dlsv-conversion-fix```. Can you confirm that?

**Comment by lemarchandarnaud** [comment]
Yes I  confirmed, I meet no auxiliarie channels anymore in the dlsv-conversion-fix
