### ISSUE TITLE
 fdsnxml2inv - import_inv dlsv : rejected units

### ISSUE THREAD

**Issue by lemarchandarnaud** [SeisComP3/seiscomp3#113]
Dear Jan
Currently only "M/S", "M/S^2", "M", "C" and "PA" are supported as input units in by the import tools. This is a real problem whe you want to deal with others kind of geophysical data.
regards
arnaud

**Comment by gempa-jabe** [comment]
This is a duplicate of #111. With *supported* you refer to the creation of Streams and not AuxStreams, right?

**Comment by lemarchandarnaud** [comment]
The dlsv-conversion-fix also sorts ou this issue but it is not exactly the same as  the issue 111 even if they likely linked.
