### ISSUE TITLE
register ABS filter

### ISSUE THREAD

**Issue by duperray** [SeisComP3/seiscomp3#117]
Hi, I need this filter, it's there but not available because not registered.

Could you please add
REGISTER_INPLACE_FILTER(AbsFilter, "ABS");

at the end of src/trunk/libs/seiscomp3/math/filter/abs.cpp

vielen dank

Pierre

**Comment by gempa-jabe** [comment]
Hi Pierre, accorrding to https://docs.gempa.de/seiscomp3/current/base/filter-grammar.html it is available via two enclosing pipes, e.g. ```|BW(4,1,5)|``` ;)

De rien
Jan

**Comment by duperray** [comment]
ach mench! I did not read carefully enough the f*!@# manual!

I close this, sorry and thx for support
