### ISSUE TITLE
millisecondes in the inventory and SC3 database.

### ISSUE THREAD

**Issue by lemarchandarnaud** [SeisComP3/seiscomp3#124]
All the millisec of starttime and endtime in the streams are rounded down to 0.
It is true that  datetime format didn't supported millisec in previous version of mysql
but it has been supported since the 5.7 version of Mysql. I guess SC3 haven't implemented
millisec because of this limitation. 
Do you plan to implement the millisec in next versions of SC3?

**Comment by gempa-jabe** [comment]
Check out the Event table. For all EventParameter tables we support microseconds by adding an additional column. This just hasn't been done for all Inventory tables. We will look into a fix for the next release.
