### ISSUE TITLE
scrttv with command line filter option

### ISSUE THREAD

**Issue by bonaime** [SeisComP3/seiscomp3#128]
Hi,

I am using scrttv with the default filter. Each time I launch scrttv, I have a small script which find the window id and then "send" the keystroke "f" to activate the filtering. It would be nice to have the option to set the filtering from the command line at launch like
--default_filter_on

**Comment by gempa-jabe** [comment]
Instead of creating such a fancy method why not creating a pull request to insert such a functionality into scrttv? ;)

The current version supports that already. Either in scrttv.cfg:

```
autoApplyFilter = true
```

or via commandline:

```
scrttv --autoApplyFilter=true
```

**Comment by bonaime** [comment]
👍
