### ISSUE TITLE
scmv and event table command line option

### ISSUE THREAD

**Issue by bonaime** [SeisComP3/seiscomp3#129]
Hi,

 Each time I launch scmv, I have a small script which find the window id and then "send" the keystroke "f10" to activate the event table. It would be nice to have the option to display the event table from the command line at launch like
--event_table
and if possible, define how many historic events to display like
--nb-events-on-event_table=5

**Comment by gempa-jabe** [comment]
This has been implemented in master. You can configure it in your cfg or via command line:

```
scmv --eventTable.visible=true
```

The number of events are not configurable but the past time span from now with ```readEventsNotOlderThan```. The value is in seconds.
