### ISSUE TITLE
SMP and inv2dlsv - Cannot create Dataless Seed from XML generated by SMP

### ISSUE THREAD

**Issue by jamesgrannell** [SeisComP3/seiscomp3#130]
Hello

I am using Gempa's SMP website to generate an Station XML file, from which I want to create the dataless seed volume using inv2dlsv.

I created a test station with Guralp CMG40T sensor (natural period = 30s - 50Hz, sensitivity = 800 V/m/s) and Guralp CMG DM24 datalogger (model = Mk3, preamp gain = Fixed, TTL Number = 23, Sample rate = 100 samples/s). I filled in the remaining fields, and exported the resulting station to XML.

When I tried to convert the resulting XML to dataless seed using inv2dlsv, the following error message was generated:

Error: float argument required, not NoneType

This message doesn't help unfortunately. I was wondering if anyone else has any experience using SMP and inv2dlsv?

Thanks
James

**Comment by gempa-jabe** [comment]
I guess that the orientation of a stream is not set. Can you check that?
