### ISSUE TITLE
Case insensitive header check

### ISSUE THREAD

**Issue by junghao** [SeisComP3/seiscomp3#132]
We've met some services that returns http headers in lower case. 
The lower case headers cause this header comparison fails :
https://github.com/SeisComP3/seiscomp3/blob/master/src/trunk/libs/seiscomp3/io/recordstream/fdsnws.cpp#L234

Since HTTP spec defines headers to be case insensitive so a case insensitive comparison should be preferred.

**Comment by gempa-jabe** [comment]
Your are right and we have to fix that. Thank you.

**Comment by junghao** [comment]
Thanks. I think there're some other header checks have to be fixed as well.

**Comment by gempa-jabe** [comment]
Correct. Furthermore https support and redirects are missing. That will be implemented as well while fixing the code.

**Comment by gempa-jabe** [comment]
I committed a fix. Please give it a try. It supports https through ```fdsnwss://``` (note the trailing 's' for SSL) as well.

**Comment by junghao** [comment]
Yes thanks it works.

However my compiler doesn't like this `typename`
src/gui-qt4/apps/scmv/eventdata.cpp:218: error: using ‘typename’ outside of template

After I removed it then it compiles.

**Comment by gempa-jabe** [comment]
Thank you for confirmation. I close the issue. I have also fixed the scmv compilation issue.
