### ISSUE TITLE
Changing Arclink user for recordstream

### ISSUE THREAD

**Issue by Jollyfant** [SeisComP3/seiscomp3#134]
Hi, we are running scwfparam that requests data from recordstream Arclink. In the logs these requests show up as guest@anywhere. Can we configure this username anywhere?

Best,
Mathijs

**Comment by andres-h** [comment]
See https://docs.gempa.de/seiscomp3/current/apps/global_recordstream.html#arclink

**Comment by Jollyfant** [comment]
Hi Andres, so putting this in global.cfg would work?

    recordstream.source = eida.orfeus-eu.org:18001?user=rrsm

**Comment by andres-h** [comment]
Yes, it would work in global, but then all programs use this username. 
Might be better to put it in scwfparam.cfg.

Maybe also include the domain (useful if the logs are combined), eg.:

recordstream.source = eida.orfeus-eu.org:18001?user=rrsm@orfeus-eu.org

**Comment by Jollyfant** [comment]
Ok cheers
