### ISSUE TITLE
scevent: Change event type to fake event/not existing

### ISSUE THREAD

**Issue by webernd** [SeisComP3/seiscomp3#16]
When an event contains only rejected origins, scevent should set the event type automatically to not existing.

**Comment by jfclinton** [comment]
How do you recognise a rejected origin in scolv?

**Comment by webernd** [comment]
Its marked with an X. 

On February 20, 2015 9:21:21 AM CET, jfclinton <notifications@github.com> wrote:
>How do you recognise a rejected origin in scolv?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SeisComP3/seiscomp3/issues/16#issuecomment-75204003

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gempa-jabe** [comment]
Postponed ...
