### ISSUE TITLE
allow simple and window time parameters in fdsn station web service

### ISSUE THREAD

**Issue by crotwell** [SeisComP3/seiscomp3#161]
Currently using both a simple time and a window time in a fdsn station web service query generates an error in seiscomp3. This is different from other implementations of the station web service. I do not believe this type of query should be prohibited and to be compatible with the fdsnws specification using a simple time like starttime along with a window time like startbefore should be allowed within a single query.

In particular, SOD currently uses queries like this to find individual channels, causing failures with data centers based on seiscomp3.

For example 

[http://geofon.gfz-potsdam.de/fdsnws/station/1/query?channel=BHZ&endafter=2011-11-01T00:00:00.000&includeavailability=false&includerestricted=false&level=station&network=GE&startbefore=2011-11-01T00:00:00.000&starttime=1993-01-01T00:00:01.000&station=BKNI](http://geofon.gfz-potsdam.de/fdsnws/station/1/query?channel=BHZ&endafter=2011-11-01T00:00:00.000&includeavailability=false&includerestricted=false&level=station&network=GE&startbefore=2011-11-01T00:00:00.000&starttime=1993-01-01T00:00:01.000&station=BKNI)

returns an error of:

```
Error 400: Bad Request

simple time and window time parameters may not be combined

Usage details are available from /fdsnws/station/1/

Request:
/fdsnws/station/1/query?channel=BHZ&endafter=2011-11-01T00:00:00.000&includeavailability=false&includerestricted=false&level=station&network=GE&startbefore=2011-11-01T00:00:00.000&starttime=1993-01-01T00:00:01.000&station=BKNI

Request Submitted:
2018-01-02T17:26:47.025622

Service Version:
1.1.1
```

**Comment by gempa-stephan** [comment]
The interpretation of the simple-time parameters (starttime, endtime) differs from the window-time parameters (startbefore, startafter, endbefore, endafter). For simple-time the spec states 

> The selection shall include any metadata epochs intersecting with the specified time range.

.. where as the window-time parameters match on the exact time borders specified.

Simple-time and window-time parameters may not be combined in the SC3 FDSNWS implementation to clearly distinguish between intersecting and exact time windows. Can you please provide an example where simple-time and window-time parameters need to be combined in order fulfill a particular use case. E.g. if starttime and endafter need to be combined, the starttime may be expressed by startbefore as well.

**Comment by crotwell** [comment]
I think I have provided a use case, that exact query was generated by a user using SOD to query the Geofon fdsn station web service. I have no doubt that any individual query that uses simple and window time parameters could be reworked to not do so, but that is not the point. The point is that the FDSN specification says these parameters are allowed, and to impose additional restrictions means SC3 is not in compliance with the specification.

I write client software, which is made much easier by having a specification that lays out exactly how the services behave. To have incompatibilities like this means that software that is coded to the specification might not work with all services claiming to implement the specification. So instead of creating a client that adheres to one specification, I have to code to the specification plus add in work-arounds for all the individual idiosyncrasies of each individual server. That kind of defeats the purpose of having a specification. 

And to turn your question around, what is the use case for actively blocking starttime from being used with endafter? If a user believes that most accurately reflects what they want, why prevent it?

**Comment by gempa-stephan** [comment]
Although I'm still not convinced of the usefulness of combined simple-time and time-window requests I follow your argument about being stand compliant.

05c2285 implements mixed simple-time and time-window requests. A new SC3 release is not scheduled yet. I will take some time for the data centers to role out this version.
