### ISSUE TITLE
Seiscomp3 fdsnxml conversion  (fdsn2xml --to-staxml) Unit standard "COUNTS" Vs "count"

### ISSUE THREAD

**Issue by salichon** [SeisComP3/seiscomp3#164]
Hi,
We are using some station-xml for which some response unit is "count":

> Response
>           InstrumentSensitivity
>             Value 427336.11778048 Value
>             Frequency 1 Frequency
>             InputUnits 
>               Name m/s**2 Name
>             /InputUnits 
>             **OutputUnits**
>              **Name count Name**
          

The reverse conversion of a corresponding sc3xml file into a station-xml provides:
> **OutputUnits**
>              **Name COUNTS Name**

Is it a problem  - Are  both names correct  and equivallent?

**Comment by gempa-jabe** [comment]
I think that both names are correct. I can't think of a problem right now.

**Comment by salichon** [comment]
Thanks Jan
so  the station xml accepts both OutputUnits as "COUNTS" and "count" 
I was thinking about the previous standard issue in stationXML with "M/S" vs "m/s"
