### ISSUE TITLE
scrttv and scmv tabs

### ISSUE THREAD

**Issue by sbonaime** [SeisComP3/seiscomp3#174]
Hi,
Is there a way to disable tabs with scrttv and scmv  ? We use them in full screen without interaction. So this space is completely useless in our usage.

Thank you  
![capture d ecran 2018-05-16 a 16-05-18 17 46 23](https://user-images.githubusercontent.com/750709/40128139-3417ac70-5931-11e8-9055-bfecb50d3a93.png)

![capture d ecran 2018-05-16 a 16-05-18 17 05 48](https://user-images.githubusercontent.com/750709/40127898-b0b8d5a2-5930-11e8-9459-ce599754f33f.png)

**Comment by gempa-jabe** [comment]
This is not a developer question, please post such questions into the users forum (https://forum.seiscomp3.org).

```
scmv --displaymode groundmotion -F
```
will display the map exclusively in fullscreen. You can also configure the displaymode in scmv.cfg. You can also set "groundmotion" to display the ground motion tab in fullscreen.

scrttv.cfg:
```
scheme.tabPosition = off
```

will remove the tabbar. You can configure that in scrttv.cfg as well.
