### ISSUE TITLE
scolv: "hide events outside ___ region" (still?) not working

### ISSUE THREAD

**Issue by filefolder** [SeisComP3/seiscomp3#176]
it is my understanding this has been a known issue for some time, however i'm not sure if a fix has been implemented anywhere recently. 

if not it would be very helpful. thanks in advance

**Comment by gempa-jabe** [comment]
This is on our todo list.

**Comment by gempa-jabe** [comment]
Hopefully fixed with a41afba4f62ccd6187e64c3298e729779ab46218. Please give it a try if possible.

**Comment by filefolder** [comment]
YES!! working great thank you!
