### ISSUE TITLE
FDSNWS Event 500

### ISSUE THREAD

**Issue by Jollyfant** [SeisComP3/seiscomp3#183]
Hi devs, when you specify the `catalog` query parameter FDNSWS-Event returns 500. It seems that somewhere `None` value is propagated to the Twisted response. Our SeisComP3 version is `2017.333.5` but it happens with older versions too. Here are some examples:

http://www.orfeus-eu.org/fdsnws/event/1/query?catalog=EMSC
http://arclink.ethz.ch/fdsnws/event/1/query?catalog=EMSC
http://rdsa.knmi.nl/fdsnws/event/1/query?catalog=EMSC

**Comment by gempa-jabe** [comment]
This is an error, correct. @gempa-stephan, please take a look.

**Comment by gempa-stephan** [comment]
Thanks for spotting this error. Please test and comment on #185
