### ISSUE TITLE
scconfig not show it

### ISSUE THREAD

**Issue by sadalsuud** [SeisComP3/seiscomp3#184]
Hi, I have installed seiscomp3 in ubuntu 16.04 and I try run scconfig, I got this message: 

`bin/scconfig: error while loading shared libraries: libseiscomp3_core.so: cannot open shared object file: No such file or directory`

But this file yes are into my system in: 

> /lib/libseiscomp3_core.so

How I can run GUI ?? ... any idea, I am new, thanks

**Comment by gempa-stephan** [comment]
You either need to run scconfig (and any other SC3 binary) via

``INSTALLDIR/bin/seiscomp exec scconfig``

or you put the output of

``INSTALLDIR/bin/seiscomp print env``

at the end of your ``~/.bashrc``, e.g.

``INSTALLDIR/bin/seiscomp print env >> ~/.bashrc``

Note: You need to start a new terminal for the changes to become effective.
