### ISSUE TITLE
improve display of problem channel info in scolv picker

### ISSUE THREAD

**Issue by jfclinton** [SeisComP3/seiscomp3#19]
in scolv picker window when using 3C option, currently if there is no difference in how problems are shown: trace is simply red and channel name is 'valid'. I propose showing that is there is missing metadata, use a different colour than if there is missing waveform data, and instead of labelling the channel a default 1,2,3, use a message as 'no metadata defined'.
(motivation: we migrate 1990s network info, that includes many 1C stations. We continue to want to see 3C if available, its now difficult to easily see if a 'red' bars means missing data or metadata.)

**Comment by gempa-jabe** [comment]
I agree.

**Comment by smallint** [comment]
Would that fulfill your needs?

![metadata](https://cloud.githubusercontent.com/assets/6400406/6483427/3b85f34a-c271-11e4-837e-f41d79179195.png)

**Comment by gempa-jabe** [comment]
Would that fulfill your needs?

![metadata](https://cloud.githubusercontent.com/assets/7439134/6483443/7e3d75fa-c271-11e4-8fce-41e2a6c80469.png)

**Comment by jfclinton** [comment]
Looks about right! Can we test this at SED?

**Comment by gempa-jabe** [comment]
Yes, here it is: 86e1c696137e5b1c873d55630e2f619633a66a10

**Comment by jfclinton** [comment]
Jan - looks fine - closing
