### ISSUE TITLE
Located events information

### ISSUE THREAD

**Issue by alirezaniki** [SeisComP3/seiscomp3#195]
Hi
Its not an issue but just a help message.
I just started using seiscomp3 to a real-time source analysis in IGUT, So I'm not expert on it. 
What I need is a text file (or other possible formats) which contains located events information (e.g Date, Time, Lat, Lon, ...), which could be seen in scesv GUI, but I failed every time I tried to find one.
Is there such a file in Seiscomp3 tree?
Could anyone give me a clue to it?
Many Thanks.

**Comment by gempa-jabe** [comment]
And welcome to the community ;)
