### ISSUE TITLE
[fdsnws] Why station magnitudes, amplitudes are not included?

### ISSUE THREAD

**Issue by jordi-domingo** [SeisComP3/seiscomp3#199]
Hi all,

One question... Why station magnitudes, amplitudes are not included in the FDSNws-event output?
Is it difficult or too expensive to obtain them? Or it has been never requested?

https://github.com/SeisComP3/seiscomp3/blob/master/src/trunk/apps/fdsnws/fdsnws/event.py#L470

**Comment by jsaul** [comment]
Jordi Domingo Ballesta wrote on 10/25/2018 03:07 PM:
> One question...

May I kindly refer you to the user forum for questions/discussions? 
Thanks a lot.

**Comment by jordi-domingo** [comment]
Sure, of course!
Sorry
