### ISSUE TITLE
nmxptool installing

### ISSUE THREAD

**Issue by barbod2543** [SeisComP3/seiscomp3#203]
Hi dears
When i use “make” for compiling this error appear:

[mehrdad@localhost nmxptool-2.1.4]$ ./configure
checking build system type… x86_64-unknown-linux-gnu
checking host system type… x86_64-unknown-linux-gnu
checking target system type… x86_64-unknown-linux-gnu
configure: BINARY_DIST_NAME_SUFFIX set to x86_64-unknown-linux-gnu
checking for a BSD-compatible install… /usr/bin/install -c
checking whether build environment is sane… yes
checking for a thread-safe mkdir -p… ./install-sh -c -d
checking for gawk… gawk
checking whether make sets $(MAKE)… yes
checking whether make supports nested variables… yes
checking whether to enable maintainer-specific portions of Makefiles… no
checking for gawk… (cached) gawk
checking for gcc… gcc
checking whether the C compiler works… yes
checking for C compiler default output file name… a.out
checking for suffix of executables…
checking whether we are cross compiling… no
checking for suffix of object files… o
checking whether we are using the GNU C compiler… yes
checking whether gcc accepts -g… yes
checking for gcc option to accept ISO C89… none needed
checking whether gcc understands -c and -o together… yes
checking for style of include used by make… GNU
checking dependency style of gcc… gcc3
checking whether ln -s works… yes
checking whether make sets $(MAKE)… (cached) yes
checking how to print strings… printf
checking for a sed that does not truncate output… /usr/bin/sed
checking for grep that handles long lines and -e… /usr/bin/grep
checking for egrep… /usr/bin/grep -E
checking for fgrep… /usr/bin/grep -F
checking for ld used by gcc… /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld… yes
checking for BSD- or MS-compatible name lister (nm)… /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface… BSD nm
checking the maximum length of command line arguments… 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format… func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format… func_convert_file_noop
checking for /usr/bin/ld option to reload object files… -r
checking for objdump… objdump
checking how to recognize dependent libraries… pass_all
checking for dlltool… no
checking how to associate runtime and link libraries… printf %s\n
checking for ar… ar
checking for archiver @FILE support… @
checking for strip… strip
checking for ranlib… ranlib
checking command to parse /usr/bin/nm -B output from gcc object… ok
checking for sysroot… no
checking for a working dd… /usr/bin/dd
checking how to truncate binary pipes… /usr/bin/dd bs=4096 count=1
checking for mt… no
checking if : is a manifest tool… no
checking how to run the C preprocessor… gcc -E
checking for ANSI C header files… yes
checking for sys/types.h… yes
checking for sys/stat.h… yes
checking for stdlib.h… yes
checking for string.h… yes
checking for memory.h… yes
checking for strings.h… yes
checking for inttypes.h… yes
checking for stdint.h… yes
checking for unistd.h… yes
checking for dlfcn.h… yes
checking for objdir… .libs
checking if gcc supports -fno-rtti -fno-exceptions… no
checking for gcc option to produce PIC… -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works… yes
checking if gcc static flag -static works… yes
checking if gcc supports -c -o file.o… yes
checking if gcc supports -c -o file.o… (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries… yes
checking whether -lc should be explicitly linked in… no
checking dynamic linker characteristics… GNU/Linux ld.so
checking how to hardcode library paths into programs… immediate
checking whether stripping libraries is possible… yes
checking if libtool supports shared libraries… yes
checking whether to build shared libraries… yes
checking whether to build static libraries… yes
checking for socket in -lnsl… no
checking for nanosleep in -lrt… yes
checking for fabs in -lm… yes
checking for puts in -lws2_32… no
configure: WARNING: Cross-compiling: no x86_64-unknown-linux-gnu x86_64-unknown-linux-gnu x86_64-unknown-linux-gnu
configure: WARNING: OSTYPE: linux-gnu
configure: WARNING: Operating system is not Windows. linux-gnu
checking for ANSI C header files… (cached) yes
checking arpa/inet.h usability… yes
checking arpa/inet.h presence… yes
checking for arpa/inet.h… yes
checking netdb.h usability… yes
checking netdb.h presence… yes
checking for netdb.h… yes
checking netinet/in.h usability… yes
checking netinet/in.h presence… yes
checking for netinet/in.h… yes
checking for stdint.h… (cached) yes
checking for stdlib.h… (cached) yes
checking for string.h… (cached) yes
checking sys/socket.h usability… yes
checking sys/socket.h presence… yes
checking for sys/socket.h… yes
checking for sys/stat.h… (cached) yes
checking sys/time.h usability… yes
checking sys/time.h presence… yes
checking for sys/time.h… yes
checking for unistd.h… (cached) yes
checking pthread.h usability… yes
checking pthread.h presence… yes
checking for pthread.h… yes
checking windows.h usability… no
checking windows.h presence… no
checking for windows.h… no
checking winsock2.h usability… no
checking winsock2.h presence… no
checking for winsock2.h… no
checking for msr_init in -lmseed… no
configure: WARNING: libmseed is not available (–disable-libmseed to disable)
configure: WARNING: Earthworm files are not available (–disable-ew to disable)
configure: WARNING: SEISCOMPDIR is set to /home/sysop/seiscomp3
checking for an ANSI C-conforming const… yes
checking for inline… inline
checking for int16_t… yes
checking for int32_t… yes
checking for int64_t… yes
checking for uint32_t… yes
checking for int8_t… yes
checking for mode_t… yes
checking for pid_t… yes
checking for size_t… yes
checking for ssize_t… yes
checking whether struct tm is in sys/time.h or time.h… time.h
checking whether time.h and sys/time.h may both be included… yes
checking for sys/time.h… (cached) yes
checking for unistd.h… (cached) yes
checking for alarm… yes
checking for working mktime… yes
checking sys/select.h usability… yes
checking sys/select.h presence… yes
checking for sys/select.h… yes
checking for sys/socket.h… (cached) yes
checking types of arguments for select… int,fd_set *,struct timeval *
checking whether strerror_r is declared… yes
checking for strerror_r… yes
checking whether strerror_r returns char *… no
checking return type of signal handlers… void
checking for getcwd… yes
checking for gethostbyname… yes
checking for inet_ntoa… yes
checking for memmove… yes
checking for memset… yes
checking for mkdir… yes
checking for select… yes
checking for setenv… yes
checking for socket… yes
checking for strcasecmp… yes
checking for strchr… yes
checking for strerror… yes
checking for strstr… yes
checking for strtol… yes
checking for tzset… yes
checking for gettimeofday… yes
checking for timegm… yes
checking for struct tm.tm_gmtoff… no
checking for global _timezone variable… no
checking whether setsockopt(SO_RCVTIMEO) is broken… no
checking that generated files are newer than configure… done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: Enabled features
libmseed : NO
SeedLink : YES
Earthworm: NO
Cross-compiling: no x86_64-unknown-linux-gnu x86_64-unknown-linux-gnu x86_64-unknown-linux-gnu
configure:
Compile nmxptool using ‘make’.
configure:
After compilation you can install nmxptool for Earthworm:
make install-ew-bin
make install-ew-conf
configure:
After compilation you can install nmxptool for Seedlink:
make install-seiscomp-bin
make install-seiscomp-templates

[mehrdad@localhost nmxptool-2.1.4]$ make
make all-recursive
make[1]: Entering directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4' Making all in lib make[2]: Entering directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4/lib’
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp.o -MD -MP -MF .deps/libnmxp_a-nmxp.Tpo -c -o libnmxp_a-nmxp.o test -f 'nmxp.c' || echo './' nmxp.c
mv -f .deps/libnmxp_a-nmxp.Tpo .deps/libnmxp_a-nmxp.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp_base.o -MD -MP -MF .deps/libnmxp_a-nmxp_base.Tpo -c -o libnmxp_a-nmxp_base.o test -f 'nmxp_base.c' || echo './' nmxp_base.c
mv -f .deps/libnmxp_a-nmxp_base.Tpo .deps/libnmxp_a-nmxp_base.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp_data.o -MD -MP -MF .deps/libnmxp_a-nmxp_data.Tpo -c -o libnmxp_a-nmxp_data.o test -f 'nmxp_data.c' || echo './' nmxp_data.c
mv -f .deps/libnmxp_a-nmxp_data.Tpo .deps/libnmxp_a-nmxp_data.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp_chan.o -MD -MP -MF .deps/libnmxp_a-nmxp_chan.Tpo -c -o libnmxp_a-nmxp_chan.o test -f 'nmxp_chan.c' || echo './' nmxp_chan.c
mv -f .deps/libnmxp_a-nmxp_chan.Tpo .deps/libnmxp_a-nmxp_chan.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp_log.o -MD -MP -MF .deps/libnmxp_a-nmxp_log.Tpo -c -o libnmxp_a-nmxp_log.o test -f 'nmxp_log.c' || echo './' nmxp_log.c
mv -f .deps/libnmxp_a-nmxp_log.Tpo .deps/libnmxp_a-nmxp_log.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp_crc32.o -MD -MP -MF .deps/libnmxp_a-nmxp_crc32.Tpo -c -o libnmxp_a-nmxp_crc32.o test -f 'nmxp_crc32.c' || echo './' nmxp_crc32.c
mv -f .deps/libnmxp_a-nmxp_crc32.Tpo .deps/libnmxp_a-nmxp_crc32.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT libnmxp_a-nmxp_memory.o -MD -MP -MF .deps/libnmxp_a-nmxp_memory.Tpo -c -o libnmxp_a-nmxp_memory.o test -f 'nmxp_memory.c' || echo './' nmxp_memory.c
mv -f .deps/libnmxp_a-nmxp_memory.Tpo .deps/libnmxp_a-nmxp_memory.Po
rm -f libnmxp.a
ar cru libnmxp.a libnmxp_a-nmxp.o libnmxp_a-nmxp_base.o libnmxp_a-nmxp_data.o libnmxp_a-nmxp_chan.o libnmxp_a-nmxp_log.o libnmxp_a-nmxp_crc32.o libnmxp_a-nmxp_memory.o
ranlib libnmxp.a
make[2]: Leaving directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4/lib' Making all in src make[2]: Entering directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4/src’
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-nmxptool.o -MD -MP -MF .deps/nmxptool-nmxptool.Tpo -c -o nmxptool-nmxptool.o test -f 'nmxptool.c' || echo './' nmxptool.c
mv -f .deps/nmxptool-nmxptool.Tpo .deps/nmxptool-nmxptool.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-nmxptool_getoptlong.o -MD -MP -MF .deps/nmxptool-nmxptool_getoptlong.Tpo -c -o nmxptool-nmxptool_getoptlong.o test -f 'nmxptool_getoptlong.c' || echo './' nmxptool_getoptlong.c
mv -f .deps/nmxptool-nmxptool_getoptlong.Tpo .deps/nmxptool-nmxptool_getoptlong.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-nmxptool_ew.o -MD -MP -MF .deps/nmxptool-nmxptool_ew.Tpo -c -o nmxptool-nmxptool_ew.o test -f 'nmxptool_ew.c' || echo './' nmxptool_ew.c
mv -f .deps/nmxptool-nmxptool_ew.Tpo .deps/nmxptool-nmxptool_ew.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-nmxptool_chanseq.o -MD -MP -MF .deps/nmxptool-nmxptool_chanseq.Tpo -c -o nmxptool-nmxptool_chanseq.o test -f 'nmxptool_chanseq.c' || echo './' nmxptool_chanseq.c
mv -f .deps/nmxptool-nmxptool_chanseq.Tpo .deps/nmxptool-nmxptool_chanseq.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-nmxptool_sigcondition.o -MD -MP -MF .deps/nmxptool-nmxptool_sigcondition.Tpo -c -o nmxptool-nmxptool_sigcondition.o test -f 'nmxptool_sigcondition.c' || echo './' nmxptool_sigcondition.c
mv -f .deps/nmxptool-nmxptool_sigcondition.Tpo .deps/nmxptool-nmxptool_sigcondition.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-nmxptool_listen.o -MD -MP -MF .deps/nmxptool-nmxptool_listen.Tpo -c -o nmxptool-nmxptool_listen.o test -f 'nmxptool_listen.c' || echo './' nmxptool_listen.c
mv -f .deps/nmxptool-nmxptool_listen.Tpo .deps/nmxptool-nmxptool_listen.Po
gcc -DHAVE_CONFIG_H -I. -I… -I…/include -g -O2 -MT nmxptool-seedlink_plugin.o -MD -MP -MF .deps/nmxptool-seedlink_plugin.Tpo -c -o nmxptool-seedlink_plugin.o test -f 'seedlink_plugin.c' || echo './' seedlink_plugin.c
mv -f .deps/nmxptool-seedlink_plugin.Tpo .deps/nmxptool-seedlink_plugin.Po
/bin/sh …/libtool --tag=CC --mode=link gcc -I…/include -g -O2 -o nmxptool nmxptool-nmxptool.o nmxptool-nmxptool_getoptlong.o nmxptool-nmxptool_ew.o nmxptool-nmxptool_chanseq.o nmxptool-nmxptool_sigcondition.o nmxptool-nmxptool_listen.o nmxptool-seedlink_plugin.o …/lib/libnmxp.a -lrt -lm
…/libtool: line 7902: func_munge_path_list: command not found
libtool: link: gcc -I…/include -g -O2 -o nmxptool nmxptool-nmxptool.o nmxptool-nmxptool_getoptlong.o nmxptool-nmxptool_ew.o nmxptool-nmxptool_chanseq.o nmxptool-nmxptool_sigcondition.o nmxptool-nmxptool_listen.o nmxptool-seedlink_plugin.o …/lib/libnmxp.a -lrt -lm
/usr/bin/ld: nmxptool-nmxptool.o: undefined reference to symbol ‘pthread_create@@GLIBC_2.2.5’
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [nmxptool] Error 1
make[2]: Leaving directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4/src' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4’
make: *** [all] Error 2
[mehrdad@localhost nmxptool-2.1.4]$

Reply

barbod2543
40m
plz answer me for this error:pensive::pensive::pensive::pensive:
/usr/bin/ld: nmxptool-nmxptool.o: undefined reference to symbol ‘pthread_create@@GLIBC_2.2.5’
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [nmxptool] Error 1
make[2]: Leaving directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4/src' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory /home/mehrdad/seiscomp3/share/plugins/seedlink/nmxptool-2.1.4’
make: *** [all] Error 2

**Comment by gempa-jabe** [comment]
nmxptool is not part of SeisComP3, it is an external application. Please contact the author of the tool. Maybe "-lpthread" is missing in the linker command line?

**Comment by barbod2543** [comment]
in which file?

**Comment by jsaul** [comment]
Which part of "Please contact the author of the tool." did you not understand?

**Comment by gempa-jabe** [comment]
Eventually in the Makefile. The project is using autotools and SeisComP is using cmake, completely different build systems. Again, please contact the author to resolve the compile issue.

**Comment by gempa-jabe** [comment]
You can create an issue at the nmxptool project page: https://gitlab.rm.ingv.it/matteo.quintiliani/nmxptool
