### ISSUE TITLE
Debian 9 dependencies

### ISSUE THREAD

**Issue by Jollyfant** [SeisComP3/seiscomp3#206]
Hi, installation on Debian stretch (9) does not work. The dependency folder seems to be missing under:

    seiscomp3/share/deps/debian/9.0/

I sort of fixed this manually by replacing the dependencies in `8.0`.

* `libboost-*1.55.0` to `libboost-*1.62.0`
* `libssl1.0.0` with `libssl1.0.2`
* `libmysqlclient18` with `libmariadb-dev`

Some dependencies seem to be installed by default and should be removed anyway.

Edit: I mean here https://www.seiscomp3.org/downloader/

**Comment by gempa-jabe** [comment]
Thanks for checking that. We will look into this. The Debian 9 dependency scripts are indeed missing.
