### ISSUE TITLE
FDSN WS interfaces report date-times on Unix epoch as invalid

### ISSUE THREAD

**Issue by chad-iris** [SeisComP3/seiscomp3#225]
It would appear that if `starttime` (and probably `endtime`, etc.) are set to exactly the Unix/POSIX epoch of 1970-01-01T00:00:00 then the times are reported as invalid.

As some examples:
https://eida.bgr.de/fdsnws/station/1/query?starttime=1970-01-01T00:00:00&format=text&level=network

https://geofon.gfz-potsdam.de//fdsnws/station/1/query?starttime=1970-01-01T00:00:00&format=text&level=network

https://fdsnws.raspberryshakedata.com/fdsnws/station/1/query?starttime=1970-01-01T00:00:00&format=text&level=network

```
Error 400: Bad Request

invalid date format in parameter: starttime

Usage details are available from /fdsnws/station/1/

Request:
/fdsnws/station/1/query?starttime=1970-01-01T00:00:00&format=text&level=network

Request Submitted:
2019-05-23T20:38:25.333945

Service Version:
1.2.0
```

If the time is shifted from the epoch value by any amount the date-times are accepted as expected.

**Comment by gempa-stephan** [comment]
A fix was implemented and a pull request was opened.
