### ISSUE TITLE
FDSN WS reporting as unspecified, incorrect version

### ISSUE THREAD

**Issue by chad-iris** [SeisComP3/seiscomp3#226]
The version reported by some SeisComP-based FDSN web services report an incorrect version, incorrect because no such version has been specified by the FDSN.

For example:
https://fdsnws.raspberryshakedata.com/fdsnws/station/1/version

Responds with:
```
1.2.0
```

But the FDSN has not specified version 1.2 of the fdnsws-station service, the latest release is version 1.1:
http://www.fdsn.org/webservices/FDSN-WS-Specifications-1.2.pdf#page=11

I can imagine this was confused because the common documentation version changed to version 1.2.  As an aside: to remedy this, the FDSN will be splitting apart the specifications for each service to clarify and allow for future divergence between the service API specifications.

**Comment by gempa-stephan** [comment]
Service specific version numbers have been introduced by 3dbd93be and are part of  [Jakarta 2018.327.p13](/SeisComP3/seiscomp3/tree/release/jakarta/2018.327.13/CHANGELOG.md)
