### ISSUE TITLE
Boost Signals library not found

### ISSUE THREAD

**Issue by morealaz** [SeisComP3/seiscomp3#228]
**Seiscomp version:** Jakarta 2018.327.13
**OS:** Arch Linux
**Boost version:** 1.69.0
```bash
-- The following required Boost components are missing:
--   * boost_signals
CMake Error at Modules/FindBoost.cmake:339 (MESSAGE):
  The Boost libraries (signals) are required!
Call Stack (most recent call first):
  src/trunk/apps/processing/scqc/seiscomp3/plugins/qc/CMakeLists.txt:17 (FIND_PACKAGE)
```
Apparently **Boost.Signal**  library is deprecated and **Boost.Signals2** succeeds it.
https://theboostcpplibraries.com/boost.signals2

**Comment by gempa-jabe** [comment]
In the master branch boost signals has been replaced with signals2 already and the dependency to the signals library has been removed. We can't do this in the 2018.327 release as it would break binary compatibility. The next release will not require boost signals anymore.

**Comment by morealaz** [comment]
thank you.
