### ISSUE TITLE
SCOLV picker slow on x2go

### ISSUE THREAD

**Issue by rannof** [SeisComP3/seiscomp3#247]
Hi,
We run SCOLV picker on UBUNTU 18.04 machine.
The picker runs smoothly on the machine. However, when accessing the machine remotely via X2GO client (https://wiki.x2go.org/doku.php), the picker is very slow and not responsive. 
When using NoMachine (https://www.nomachine.com/) remotely - the client runs smoothly again. Both clients/servers use NX protocol (though a bit differently) which is faster than X11 tunnel.
Our main goal is to have one server with Seiscomp3 and multiple sessions using it remotely (e.g. from a windows machine).
My question is - has anyone have a better solution for remote access to SCOLV or a fix for this issue of sluggish SCOLV? 
We think it might be related to QT4 on X2GO and that might  be fixed by moving to QT5. Is there any plan to do so?

**Comment by gempa-jabe** [comment]
Please use the forums (https://forum.seiscomp3.orgt) for such kind of questions. The Github issues are for development.
