### ISSUE TITLE
Bug in FDSNWS configuration

### ISSUE THREAD

**Issue by GarryLai** [SeisComP3/seiscomp3#248]
When I set the evaluation mode in FDSNWS configuration file. The FDSNWS service could not start but it didn't recorded any error in log file (with log level 4). Is this a bug?

**Comment by gempa-stephan** [comment]
I can't reproduce your observation. Which FDSNWS version are you running?

I tested the FDSNWS with
*  empty evaluationMode 
* `evaluationMode = manual`
* `evaluationMode = automatic`
* `evaluationMode = foo`

The first 3 cases returned the expected result for an event query. In the last case the FDSNWS refused to start with the error message:

`invalid evaluation mode string: foo`

**Comment by GarryLai** [comment]
Oh sorry, I mistook evaluation mode for evaluation status. But is there any way to restrict evaluation status in FDSNWS?

**Comment by gempa-jabe** [comment]
No, you can't do that.
