### ISSUE TITLE
Bug in author in scolv

### ISSUE THREAD

**Issue by ppp503** [SeisComP3/seiscomp3#249]
As long as I use command
> scolv --user someone

to start scolv, but when I confirm a event, author always bocame "scolv@sc3"

**Comment by comoglu** [comment]
use "--author" instead.

**Comment by ppp503** [comment]
"--author" doesn't work with release 2018.327 P16

**Comment by comoglu** [comment]
"scolv -u user1 --author=author1"
Should work.

Mustafa
@mobile

**Comment by gempa-jabe** [comment]
This issue tracker is for development and not user questions. Please go to the forums at https://forum.seiscomp3.org.
