### ISSUE TITLE
libpng warning iCCP issues / scconfig info_small.png

### ISSUE THREAD

**Issue by filefolder** [SeisComP3/seiscomp3#250]
minor issue but somewhat annoying error when using scconfig, which gives terminal error

`libpng warning: iCCP: known incorrect sRGB profile`

i've tracked this down to: 

sc3-src/src/trunk/apps/tools/scconfig/icons/info_small.png 

can be solved (with libpng >=1.6) by using imagemagick's mogrify

`mogrify sc3-src/src/trunk/apps/tools/scconfig/icons/info_small.png `

there's also some problems (iCCP: extra compressed data) with the png files in 

sc3-src/src/ipgp/plugins/locator/hypo71/descriptions/media/hypo71

which can be fixed in the same way

`mogrify sc3-src/src/ipgp/plugins/locator/hypo71/descriptions/media/hypo71/*.png`

more info here
https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

**Comment by gempa-jabe** [comment]
Thanks a lot for figuring that out. We will correct the images accordingly.
