### ISSUE TITLE
choosing magnitude types on summary page on scolv

### ISSUE THREAD

**Issue by comoglu** [SeisComP3/seiscomp3#254]
Hi there,
At the moment there is no place to be able to choose magnitude types to display on scolv summary page which we activate with F8. This option is available scesv, It would be handy if it is available on scolv as well. 
Thanks

**Comment by gempa-jabe** [comment]
Please note that this is a place for developers and not for feature requests. Have you ever tried `visibleMagnitudes = A,B,C` in `scolv.cfg`?
