### ISSUE TITLE
typo bug in fdsnws.py - stops fdsn if useArclinkAccess enabled 

### ISSUE THREAD

**Issue by filefolder** [SeisComP3/seiscomp3#261]
cross posted from the forum

src/trunk/apps/fdsnws/fdsnws.py line 855

`self.access = Access() if self._useArclinkAccess else None`

i think that should be self._access

**Comment by gempa-jabe** [comment]
Thanks a lot, we are going to fix that.

**Comment by gempa-jabe** [comment]
Fixed with 1fd46da6347dc66973cf2c0d645cdf907569ad18.
