### ISSUE TITLE
slmon Python3 support

### ISSUE THREAD

**Issue by a-oth** [SeisComP3/seiscomp3#267]
When I try to run slmon using Python3, it crashes with numerous syntax errors referring to myconfig.py & slclient.py. It seems that these files have not been included in the Python3 support modifications?

**Comment by gempa-jabe** [comment]
Correct, slmon has not been fully ported yet. We accept pull requests ;)

**Comment by a-oth** [comment]
Ok, thanks for letting me know ;)

**Comment by gempa-jabe** [comment]
@jsaul has made some fixes. Please try again.

**Comment by a-oth** [comment]
Many thanks @jsaul and @gempa-jabe, I will not get around to it today anymore, but will try to check tomorrow and let you know!

**Comment by a-oth** [comment]
Hello, sorry for the delayed response. I finally tested it and it works, many thanks!
