### ISSUE TITLE
missing file scgitinit.sh

### ISSUE THREAD

**Issue by marcopovitch** [SeisComP3/seiscomp3#27]
during make install 

it seems that scgitinit.sh is missing ....

-- Up-to-date: /home/sysop/seiscomp3/bin/msrtsimul
CMake Error at src/utils/apps/cmake_install.cmake:40 (FILE):
  file INSTALL cannot find
  "/home/sysop/github/seiscomp3-geoth/src/utils/apps/scgitinit.sh".
Call Stack (most recent call first):
  src/utils/cmake_install.cmake:38 (INCLUDE)
  src/cmake_install.cmake:41 (INCLUDE)
  cmake_install.cmake:37 (INCLUDE)

**Comment by gempa-jabe** [comment]
Sorry Marc, I added the missing file.
