### ISSUE TITLE
Compile on Debian 11

### ISSUE THREAD

**Issue by marcelobianchi** [SeisComP3/seiscomp3#282]
Was trying to compile the sc3 on Debian 11 w/ gcc 10 + boost 1.74 and needed to change the file:

src/gui-qt4/libs/seiscomp3/gui/map/layers/geofeaturelayer.cpp

Adding the line:

#include <boost/bind.hpp>

I not so sure but i guess it is missing somehow to be able to use the _1 feature. Does not make any sense to me to add a merge request for that, specially that I don't have a clue about it so I am leaving an issue here.

-Mb

**Comment by gempa-jabe** [comment]
Thank you Marcelo for letting us know. Does just replacing `_1` with `boost::placeholders::_1` work without including the header?

**Comment by marcelobianchi** [comment]
Yes, it does work. 

![image](https://user-images.githubusercontent.com/5138769/130439491-71abc15c-1a0d-4d2d-87db-299731bc4ed6.png)

Thank  you!

**Comment by gempa-jabe** [comment]
I pushed the fix. Btw, SeisComP (>= 4) includes it already ;)
