### ISSUE TITLE
Seedlink time out error

### ISSUE THREAD

**Issue by BRseis** [SeisComP3/seiscomp3#284]
Hello.

We are using seiscomp4 and recently we are having issues with our waveforms that disconnects and resumes after random time, sometimes minutes sometimes even hours.
It happens randomly, all the network stats are ok but still it gives timeout as displayed in the seedlink log
"socket connect error, and socket connect timeout"
We have an internal seedlink server to provide us local data and this one doesn't fail, the others that we retrieve through their seedlink servers gives us this error, even though one international server doesn't give us errors.
It looks very strange and unexplained

Hope you can help.
Thank you in advance

**Comment by gempa-jabe** [comment]
Please report such issues at https://forum.seiscomp.de. Also note that this is the repository for SeisComP3 which reached end of life. SeisComP >= 4 continues at https://github.com/seiscomp.
