### ISSUE TITLE
scolv magnitude select bug

### ISSUE THREAD

**Issue by yannikbehr** [SeisComP3/seiscomp3#53]
When selecting certain streams in scolv's magnitude window to then deselect them, the wrong streams are de-selected if the order of the streams is not by distance.
![select_bug_1](https://cloud.githubusercontent.com/assets/2305224/13372033/8b83f514-dd36-11e5-89f5-97486a1c168b.png)
![select_bug_2](https://cloud.githubusercontent.com/assets/2305224/13372032/8b839e2a-dd36-11e5-9d5f-690710701334.png)

**Comment by gempa-jabe** [comment]
Confirmed and fixed. Please check.

**Comment by yannikbehr** [comment]
Works, thanks.
