### ISSUE TITLE
scimport does not import comments

### ISSUE THREAD

**Issue by yannikbehr** [SeisComP3/seiscomp3#62]
It seems like scimport is ignoring comments. I am importing Magnitudes that have additional information attached to as comments. The comments, however, do not show up in the database and scimport's log file shows lines like the following:

```
2016/05/09 00:53:55 [debug/ScImport] Filter for class: Comment not available
```

**Comment by gempa-jabe** [comment]
That is right, scimport does not import comments. Adding a filter in the code is easy, the difficulty is to filter comments for various parent types. We could either import all or no comments. So the best would be to add an option to allow import of comments or not.

**Comment by yannikbehr** [comment]
Would it cause problems if a comment is imported but not its parent?
