### ISSUE TITLE
scevtlog does not log FocalMechanism to XML

### ISSUE THREAD

**Issue by gempa-jabe** [SeisComP3/seiscomp3#66]
Issue reported by @salichon, track it here to not forget. scevtlog does neither export the focal mechanism nor the origin of preferred magnitude if it is not part of the preferred origin.

**Comment by gempa-jabe** [comment]
I fixed that with 14db7a4e39b01936279c39b526d5d860c0e7b1f8. I have been running scevtlog for three days, gathered a lot of XML and all events with a preferred focal mechanism do contain a FocalMechanism including the derived origin with magnitudes.

**Comment by quiffman** [comment]
Thanks @gempa-jabe!

I can give this a try with @salichon and report back if you like.

**Comment by salichon** [comment]
Hey Jan
Thanks for that quick update!
I ll run that asap
Cheers
Jerome

**Comment by salichon** [comment]
@gempa-jabe, @quiffman  We made some tests: the xml files are logged okay comprising the focalmechanism solutions  and the Derived origins. I haven't seen any issue on my side.
Thanks for the fix.

**Comment by gempa-jabe** [comment]
Thank you for testing. I close this issue then.
