### ISSUE TITLE
Magnitude depth out of  range and related  status ?

### ISSUE THREAD

**Issue by salichon** [SeisComP3/seiscomp3#70]
The magnitude pop up window doesn't return a status if the depth is out of  the magnitudes range.

1- The calculated amplitude window in the GUI scolv shows a notification when the event distance (epicentral/hypocentral) is out of range but doesn't show any status when the depth is out of the magnitude range. instead it displays a "waiting for data" error message . 
The maximum magnitude calibration functions are bounded up to a depth of <= 699 km. 

2- The GUI scolv fixed depth option allows for a fixed depth depth up to 750 km.
As a consequence: Between [700-750] km depth no magnitude is allocated (if these depths are relevant... ) 
NB: using a Local magnitude(s) ( with only  the epicenter distances ) can work if close enough.

See below for a depth fixed at 701 km at regional distance over a wide selection of magnitudes. 

![magnitudedepthoutofrange](https://cloud.githubusercontent.com/assets/1953345/17421204/19927608-5afc-11e6-9dd4-99e09d7c12c4.png)

**Comment by gempa-jabe** [comment]
I have tested it with origins out of the allowed depth range and it worked (error: depth out of range). Maybe your time window moved to far so that data was not found in your archive. "Waiting for data" actually means that the data time window isn't completed after data retrieval finished.
