### ISSUE TITLE
scolv events tab pop-up event info window 

### ISSUE THREAD

**Issue by salichon** [SeisComP3/seiscomp3#75]
An option to dismiss the yellow pop-up window in the events tab would be useful to set:
While selecting or inspecting events this pop-up window is not convenient since appearing each time the cursor is sat on an event.

![pop-up windowsc3](https://cloud.githubusercontent.com/assets/1953345/18767286/5bc686da-8172-11e6-8c8c-c1043ab76e71.png)

**Comment by gempa-jabe** [comment]
Rather than adding an additional configuration option I would prefer to show the tooltip only if the ID column is being hovered.

**Comment by salichon** [comment]
Great
 i saw this updated in the 2017.334 patch 1 
[https://github.com/SeisComP3/seiscomp3/blob/release/jakarta/CHANGELOG.md](url)
thanks  for this update 
i ll test it  with local compilation and close the ticket ;)  
Cheers
Jerome

**Comment by salichon** [comment]
@gempa-jabe  sorry for the late confirmation.
All good tool tip shown on  the ID only.
nice thanks
