### ISSUE TITLE
scenvelope 

### ISSUE THREAD

**Issue by comoglu** [SeisComP3/seiscomp3#80]
I just compiled the latest git version, everything seems ok except scenvelope. 
database version incompatibility.

2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped
2016/10/15 09:27:11 [error/Communication] failed to serialize archive
2016/10/15 09:27:11 [error/DataModel] Archive version 0.9 too high: Envelope skipped

**Comment by gempa-jabe** [comment]
Thanks Mustafa: The Git is still work in progress and we will fix that issue.

**Comment by gempa-jabe** [comment]
Try the latest commit 0ebd49d2c8ab5bdf87dd03679919bcf9805d4f04 which should fix it.

**Comment by comoglu** [comment]
Could you remind me How can I apply the fixes? long time has passed since I have applied a patch. 
Thanks so much.

**Comment by gempa-jabe** [comment]
Just pull the lastest git version, thats all.

**Comment by comoglu** [comment]
then compile again, isnt it. 
OK I ll do that. 
Thanks Jan.

**Comment by comoglu** [comment]
Yep it works now. Thanks
